/**
 * Nepal category locale data (PRD Appendix A). Nepali names are proposals
 * needing native-speaker review. Aliases are search-only and never shown.
 */

export const NEPALI_CATEGORY_NAMES: Record<string, string> = {
  food: 'खाना',
  groceries: 'किराना / तरकारी',
  rent: 'कोठा भाडा',
  electricity: 'बिजुली',
  water: 'खानेपानी',
  internet_mobile: 'इन्टरनेट / मोबाइल',
  transport: 'यातायात',
  fuel: 'इन्धन',
  shopping: 'किनमेल',
  clothing: 'कपडा',
  health: 'स्वास्थ्य / औषधि',
  education: 'शिक्षा',
  entertainment: 'मनोरञ्जन',
  travel: 'यात्रा',
  personal_care: 'व्यक्तिगत हेरचाह',
  family: 'परिवार',
  gifts_social: 'उपहार / सामाजिक',
  festival: 'चाडपर्व',
  religion_donation: 'धर्म / दान',
  loan_emi: 'ऋण / किस्ता',
  insurance: 'बिमा',
  tax_fees: 'कर / शुल्क',
  subscriptions: 'सदस्यता',
  adjustment: 'समायोजन',
  'other-expense': 'अन्य',
  salary: 'तलब',
  bonus: 'बोनस / भत्ता',
  business: 'व्यापार / व्यवसाय',
  freelance: 'फ्रिलान्स',
  remittance: 'रेमिट्यान्स',
  rent_received: 'भाडा आम्दानी',
  interest_dividend: 'ब्याज / लाभांश',
  pocket_money: 'जेब खर्च',
  gift: 'उपहार',
  refund: 'फिर्ता',
  'other-income': 'अन्य',
};

export const CATEGORY_SEARCH_ALIASES: Record<string, string[]> = {
  food: ['khana', 'bhojan', 'momo', 'chiya', 'tiffin'],
  groceries: ['kirana', 'tarkari', 'saaman'],
  rent: ['bhada', 'kotha', 'ghar bhada'],
  electricity: ['bijuli', 'nea'],
  water: ['pani', 'khanepani'],
  internet_mobile: ['recharge', 'data', 'wifi', 'ntc', 'ncell', 'worldlink'],
  transport: ['bus', 'micro', 'tempo', 'taxi', 'ride'],
  fuel: ['petrol', 'diesel'],
  shopping: ['kinmel', 'bazaar'],
  clothing: ['kapada'],
  health: ['aushadhi', 'hospital', 'doctor', 'pharmacy'],
  education: ['fee', 'tuition', 'college', 'school', 'kitab'],
  entertainment: ['movie', 'cinema', 'game'],
  travel: ['yatra', 'trip', 'ticket'],
  personal_care: ['salon', 'parlour'],
  family: ['ghar', 'bachcha'],
  gifts_social: ['upahar', 'bhoj', 'bibaha', 'tika'],
  festival: ['dashain', 'tihar', 'chadparva'],
  religion_donation: ['daan', 'puja', 'mandir'],
  loan_emi: ['kista', 'rin', 'emi'],
  insurance: ['bima'],
  tax_fees: ['kar', 'shulka'],
  subscriptions: ['netflix', 'youtube', 'spotify'],
  adjustment: ['reconcile'],
  'other-expense': ['anya'],
  salary: ['talab'],
  bonus: ['bhatta', 'dashain bonus'],
  business: ['byapar', 'byabasaya'],
  freelance: ['project', 'gig'],
  remittance: ['remit', 'videsh'],
  rent_received: ['bhada'],
  interest_dividend: ['byaj', 'labhansh'],
  pocket_money: ['jeb kharcha', 'allowance'],
  gift: ['upahar'],
  refund: ['pharta', 'cashback'],
  'other-income': ['anya'],
};
